name = "charity-tracker-api"
main = "src/index.js"
compatibility_date = "2024-08-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "charity-tracker"
database_id = "your-d1-database-id" # Replace with actual D1 database ID

# R2 Storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "charity-tracker-files"

# KV Storage for sessions and caching
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id" # Replace with actual KV namespace ID
preview_id = "your-preview-kv-namespace-id"

# Environment variables
[vars]
STRIPE_PUBLISHABLE_KEY = "pk_test_..." # Replace with your Stripe key
FRONTEND_URL = "https://charity-tracker.pages.dev"
JWT_SECRET = "your-jwt-secret-here"
ENVIRONMENT = "development"
ENABLE_PAYMENT_ENFORCEMENT = "false"  # Disable payment limits for development
ENABLE_STOCK_PRICING = "true"
ENABLE_CRYPTO_PRICING = "true"
ENABLE_ADMIN_PANEL = "true"

# Production environment
[env.production]
name = "charity-tracker-api-prod"

[env.production.vars]
STRIPE_PUBLISHABLE_KEY = "pk_live_..." # Production Stripe key
FRONTEND_URL = "https://charitytracker.com"
JWT_SECRET = "production-jwt-secret"
ENVIRONMENT = "production"
ENABLE_PAYMENT_ENFORCEMENT = "true"  # Enable payment limits in production
ENABLE_STOCK_PRICING = "true"
ENABLE_CRYPTO_PRICING = "true"
ENABLE_ADMIN_PANEL = "true"

# Scheduled events for cleanup tasks
[[triggers]]
crons = ["0 2 * * *"] # Daily at 2 AM UTC